### ISSUE TITLE
Excellent mod, but would like an inclusion for an item

### ISSUE THREAD

**Issue by NyarlathotepZERO** [emipa606/DisplayCases#2]
![image](https://github.com/emipa606/DisplayCases/assets/26475624/9988c224-60bf-41d8-b1e8-59cc16e11045)
 
Ambrandy from Vanilla Brewing Mod.

As the description for it goes "Glitterworld aristocrats have been known to send entire private militias just to transport a single bottle" I think this would be worthy of earning a place in your display cabinet.

**Comment by emipa606** [comment]
Sounds good, added Luxury spirits-category as possible to display.
Published in 6425a0f

**Comment by NyarlathotepZERO** [comment]
There are not-so-subtle variations between laying items in a zone on the floor, and laying in the display cabinet, is this a known feature ?
![Screenshot 2023-09-12 113853](https://github.com/emipa606/DisplayCases/assets/26475624/2be3df2d-63a8-45af-9dfb-5bae137c2c63)
![Screenshot 2023-09-12 113715](https://github.com/emipa606/DisplayCases/assets/26475624/a47e8d49-dab9-4f63-9333-1aae133e29c5)

**Comment by emipa606** [comment]
I dont understand the question?

**Comment by NyarlathotepZERO** [comment]
My apologies, I thought that the display was supposed to show the beauty of the objects within. These 2 screenshots are the same item, but one has the item in a stockpile on the ground and the other has the item in the display case. The one in the display case is a 'less beautiful' room as shown by the beauty factor. (2.8 vs 14)

**Comment by emipa606** [comment]
Ah, I see. Yes there seems to be a mistake here. The cases should not have the `ignoreStoredThingsBeauty` setting set to true. Ill fix it

**Comment by emipa606** [comment]
Should be fixed in 2afa750
